version: "3.7"
services:
  mysql:
    container_name: todo-mysql
    image: dw1m2g25/report_dw1_m2:todo-mysql
    build:
      context: .
      dockerfile: ./dockerfile.mysql
    command:
      - --character-set-server=utf8mb4
      - --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
    networks:
      - todo-network
    ports:
      - 3306:3306

  app:
    depends_on:
      - mysql
    container_name: todo-app
    image: dw1m2g25/report_dw1_m2:todo-app
    build:
      context: .
      dockerfile: ./dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 8080:8080
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge